### ISSUE TITLE
[Bug]: Failed to render GraphBuilder (Ubuntu)

### ISSUE THREAD

**Issue by advisely** [Ironclad/rivet#130] opened 2023-09-13 02:23 UTC
### What happened?

I can't use the GUI, everything disappear once I select an action - and an error message shows in the interface: Failed to render GraphBuilder

### What was the expected functionality?

The plain UI to be visible, action created to be visible and not blurred, right-clic to work as well.

### Describe your environment

Ubuntu v23.04
Yarn v4.0.0-rc.45
node v20.6.1
npm v9.8.1
react v18.2.0

### Relevant log output

```shell
/rivet$ yarn
➤ YN0000: ┌ Project validation
➤ YN0057: │ @ironclad/rivet-app: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide @algolia/client-search (pbc410), requested by @algolia/autocomplete-shared
➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide algoliasearch (p8ad5b), requested by @algolia/autocomplete-shared
➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide search-insights (pfdb70), requested by @algolia/autocomplete-plugin-algolia-insights
➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide @algolia/client-search (pdf3b9), requested by @algolia/autocomplete-shared
➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide algoliasearch (p0f6bb), requested by @algolia/autocomplete-shared
➤ YN0002: │ @atlaskit/modal-dialog@npm:12.6.9 [388c2] doesn't provide react-dom (pa1855), requested by @atlaskit/portal
➤ YN0002: │ @atlaskit/popper@npm:5.5.4 [9ee97] doesn't provide react-dom (p9dacd), requested by react-popper
➤ YN0002: │ @atlaskit/side-navigation@npm:2.0.4 [388c2] doesn't provide react-dom (p5f5ce), requested by @atlaskit/menu
➤ YN0002: │ @docsearch/react@npm:3.5.2 [45935] doesn't provide @algolia/client-search (p8cbb4), requested by @algolia/autocomplete-preset-algolia
➤ YN0002: │ @ironclad/rivet-app@workspace:packages/app doesn't provide @typescript-eslint/parser (p52c17), requested by @typescript-eslint/eslint-plugin
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p0d8ba) with version 18.2.0, which doesn't satisfy what @atlaskit/tokens requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p09bd4) with version 18.2.0, which doesn't satisfy what @atlaskit/theme requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p47042) with version 18.2.0, which doesn't satisfy what @atlaskit/icon requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p6c641) with version 18.2.0, which doesn't satisfy what @atlaskit/button and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p613bc) with version 18.2.0, which doesn't satisfy what @atlaskit/menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p57ddd) with version 18.2.0, which doesn't satisfy what @atlaskit/popup requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p010de) with version 18.2.0, which doesn't satisfy what @atlaskit/form and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p664cc) with version 18.2.0, which doesn't satisfy what @atlaskit/textfield requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pbeed5) with version 18.2.0, which doesn't satisfy what @atlaskit/portal requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p12a65) with version 18.2.0, which doesn't satisfy what @atlaskit/banner and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p9cf70) with version 18.2.0, which doesn't satisfy what @atlaskit/checkbox requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pb1f52) with version 18.2.0, which doesn't satisfy what @atlaskit/css-reset requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p00d1e) with version 18.2.0, which doesn't satisfy what @atlaskit/dropdown-menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pc6d35) with version 18.2.0, which doesn't satisfy what @atlaskit/inline-edit and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p720fb) with version 18.2.0, which doesn't satisfy what @atlaskit/modal-dialog and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p8de0e) with version 18.2.0, which doesn't satisfy what @atlaskit/select and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pd7499) with version 18.2.0, which doesn't satisfy what @atlaskit/side-navigation and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p69491) with version 18.2.0, which doesn't satisfy what @atlaskit/tabs requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p5c2ae) with version 18.2.0, which doesn't satisfy what @atlaskit/textarea requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p23a63) with version 18.2.0, which doesn't satisfy what @atlaskit/toggle requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (pe223a) with version 18.2.0, which doesn't satisfy what @atlaskit/menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (pea2fd) with version 18.2.0, which doesn't satisfy what @atlaskit/popup requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (p39d52) with version 18.2.0, which doesn't satisfy what @atlaskit/portal requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (pa1f4f) with version 18.2.0, which doesn't satisfy what @atlaskit/dropdown-menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (p51537) with version 18.2.0, which doesn't satisfy what @atlaskit/select and some of its descendants request
➤ YN0002: │ @ironclad/rivet-core@workspace:packages/core doesn't provide @types/node (p2a077), requested by ts-node
➤ YN0002: │ @ironclad/rivet-core@workspace:packages/core doesn't provide @typescript-eslint/parser (pcafdb), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ @ironclad/rivet-node@workspace:packages/node doesn't provide @typescript-eslint/parser (p5d7b8), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ @ironclad/rivet@workspace:. doesn't provide @typescript-eslint/parser (p14739), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ @ironclad/trivet@workspace:packages/trivet doesn't provide @typescript-eslint/parser (pc3af5), requested by @typescript-eslint/eslint-plugin
➤ YN0060: │ docs@workspace:packages/docs provides react (p4e1cc) with version 18.2.0, which doesn't satisfy what @docusaurus/types requests
➤ YN0060: │ docs@workspace:packages/docs provides react (p9d5e3) with version 18.2.0, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0060: │ docs@workspace:packages/docs provides react (p1334f) with version 18.2.0, which doesn't satisfy what @mdx-js/react requests
➤ YN0060: │ docs@workspace:packages/docs provides react (p0e283) with version 18.2.0, which doesn't satisfy what @docusaurus/preset-classic and some of its descendants request
➤ YN0060: │ docs@workspace:packages/docs provides react-dom (p1a640) with version 18.2.0, which doesn't satisfy what @docusaurus/types requests
➤ YN0060: │ docs@workspace:packages/docs provides react-dom (p47f6f) with version 18.2.0, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0060: │ docs@workspace:packages/docs provides react-dom (p45133) with version 18.2.0, which doesn't satisfy what @docusaurus/preset-classic and some of its descendants request
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [388c2] doesn't provide @babel/plugin-syntax-flow (p32599), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [388c2] doesn't provide @babel/plugin-transform-react-jsx (pff2ca), requested by eslint-plugin-flowtype
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 298ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 331ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 502ms
➤ YN0000: Done with warnings in 1s 215ms
/rivet$ yarn dev
Bundling to bin/executor-bundle.js...
Compiling to native binary for linux...
> pkg@5.8.1
> Warning Cannot resolve 'config.extends'
  rivet/packages/app-executor/bin/executor-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'path2'
  /rivet/packages/app-executor/bin/executor-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
Copied dist/rivet-app-executor to dist/app-executor-x86_64-unknown-linux-gnu for tauri sidecar
     Running BeforeDevCommand (`yarn start`)

  VITE v4.4.9  ready in 390 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
        Info Watching /rivet/packages/app/src-tauri for changes...
   Compiling glib-sys v0.15.10
   Compiling gobject-sys v0.15.10
   Compiling gdk-sys v0.15.1
   Compiling gio-sys v0.15.10
   Compiling atk-sys v0.15.1
   Compiling cairo-sys-rs v0.15.1
   Compiling pango-sys v0.15.10
   Compiling gdk-pixbuf-sys v0.15.10
   Compiling soup2-sys v0.2.0
   Compiling openssl-sys v0.9.91
   Compiling javascriptcore-rs-sys v0.4.0
   Compiling x11-dl v2.21.0
   Compiling app v0.1.0 (/rivet/packages/app/src-tauri)
   Compiling openssl v0.10.56
   Compiling native-tls v0.2.11
   Compiling gtk-sys v0.15.3
   Compiling gdkx11-sys v0.15.1
   Compiling tao v0.16.2
   Compiling gtk v0.15.5
   Compiling webkit2gtk-sys v0.18.0
   Compiling rfd v0.10.0
   Compiling wry v0.24.3
   Compiling glib v0.15.12
   Compiling gdkwayland-sys v0.15.3
   Compiling tokio-native-tls v0.3.1
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.19
   Compiling gio v0.15.12
   Compiling cairo-rs v0.15.12
   Compiling pango v0.15.10
   Compiling atk v0.15.1
   Compiling javascriptcore-rs v0.16.0
   Compiling gdk-pixbuf v0.15.11
   Compiling soup2 v0.2.1
   Compiling gdk v0.15.4
   Compiling webkit2gtk v0.18.2
   Compiling tauri-runtime v0.14.0
   Compiling tauri-runtime-wry v0.14.0
   Compiling tauri v1.4.1
   Compiling tauri-plugin-persisted-scope v0.1.0 (https://github.com/tauri-apps/plugins-workspace?branch=dev#dce0f02b)
   Compiling tauri-plugin-window-state v0.1.0 (https://github.com/tauri-apps/plugins-workspace?branch=v1#6647e6ea)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 01s
10:04:54 PM [vite] warning: 
/rivet/packages/app/src/hooks/useProjectPlugins.ts
27 |                throw new Error(`Unknown built-in plugin ${name}.`);
28 |              }).with({ type: "uri" }, async (spec2) => {
29 |                const plugin = (await import(spec2.uri)).default;
   |                                             ^
30 |                if (!plugin?.id) {
31 |                  throw new Error(`Plugin ${spec2.id} does not have an id`);
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

  Plugin: vite:import-analysis
  File: /rivet/packages/app/src/hooks/useProjectPlugins.ts
```

### Relevant screenshots

![image](https://github.com/Ironclad/rivet/assets/29242247/1e6090ff-43f9-4a27-9349-4b98daea71ac)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abrenneke** [comment] 2023-09-13 03:16
Seems that Ubuntu has a lot of problems with Rivet for some reason.

**Comment by entvia** [comment] 2023-09-13 20:00
Same here, Ubuntu

**Comment by abrenneke** [comment] 2023-09-14 17:13
The main ubuntu bug should be fixed in the upcoming 1.2.1. You might still get the weird GraphBuilder error, so can you reopen this if the problem is still present in 1.2.1? @all-contributors please add @advisely for bug

**Closed by abrenneke** 2023-09-14 17:13 UTC
Labels: bug, help wanted

**Comment by abrenneke** [comment] 2023-09-14 17:14
let's try that again, @all-contributors please add @advisely for bug

**Comment by advisely** [comment] 2023-09-14 17:42
It's my first time using the app and reporting the bug?! Can the bot show where I contributed before?

**Comment by abrenneke** [comment] 2023-09-14 17:43
hey, a bug report is a contribution in my mind! I don't think it can do that, unfortunately

**Comment by advisely** [comment] 2023-09-14 20:22
Gotcha, thank you!

**Comment by advisely** [comment] 2023-09-14 20:31
looks like it's fixed with the new update! Thanks!!

![image](https://github.com/Ironclad/rivet/assets/29242247/b3c567db-52ae-4aee-93c3-e5e09d31dc15)

rivet$ yarn
➤ YN0000: ┌ Project validation
➤ YN0057: │ @ironclad/rivet-app: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide @algolia/client-search (pbc410), requested by @algolia/autocomplete-shared
➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide algoliasearch (p8ad5b), requested by @algolia/autocomplete-shared
➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide search-insights (pfdb70), requested by @algolia/autocomplete-plugin-algolia-insights
➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide @algolia/client-search (pdf3b9), requested by @algolia/autocomplete-shared
➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide algoliasearch (p0f6bb), requested by @algolia/autocomplete-shared
➤ YN0002: │ @atlaskit/modal-dialog@npm:12.6.4 [388c2] doesn't provide react-dom (p71a81), requested by @atlaskit/portal
➤ YN0002: │ @atlaskit/popper@npm:5.5.3 [af08a] doesn't provide react-dom (pe6a9b), requested by react-popper
➤ YN0002: │ @atlaskit/side-navigation@npm:2.0.3 [388c2] doesn't provide react-dom (pe90e8), requested by @atlaskit/menu
➤ YN0002: │ @docsearch/react@npm:3.5.1 [45935] doesn't provide @algolia/client-search (pc8a10), requested by @algolia/autocomplete-preset-algolia
➤ YN0002: │ @ironclad/rivet-app@workspace:packages/app doesn't provide @typescript-eslint/parser (p52c17), requested by @typescript-eslint/eslint-plugin
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pbd4a5) with version 18.2.0, which doesn't satisfy what @atlaskit/tokens requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p09bd4) with version 18.2.0, which doesn't satisfy what @atlaskit/theme requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p47042) with version 18.2.0, which doesn't satisfy what @atlaskit/icon requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pc7cba) with version 18.2.0, which doesn't satisfy what @atlaskit/button and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p613bc) with version 18.2.0, which doesn't satisfy what @atlaskit/menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p281dc) with version 18.2.0, which doesn't satisfy what @atlaskit/popup requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pad932) with version 18.2.0, which doesn't satisfy what @atlaskit/form and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p318a7) with version 18.2.0, which doesn't satisfy what @atlaskit/textfield requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pc532f) with version 18.2.0, which doesn't satisfy what @atlaskit/portal requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p47850) with version 18.2.0, which doesn't satisfy what @atlaskit/banner and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p7d69a) with version 18.2.0, which doesn't satisfy what @atlaskit/checkbox requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pb1f52) with version 18.2.0, which doesn't satisfy what @atlaskit/css-reset requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p25415) with version 18.2.0, which doesn't satisfy what @atlaskit/dropdown-menu and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pde336) with version 18.2.0, which doesn't satisfy what @atlaskit/inline-edit and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p15f9e) with version 18.2.0, which doesn't satisfy what @atlaskit/modal-dialog and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (pf703f) with version 18.2.0, which doesn't satisfy what @atlaskit/select and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p39fd4) with version 18.2.0, which doesn't satisfy what @atlaskit/side-navigation and some of its descendants request
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p67a5d) with version 18.2.0, which doesn't satisfy what @atlaskit/tabs requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p581bd) with version 18.2.0, which doesn't satisfy what @atlaskit/textarea requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react (p35fc4) with version 18.2.0, which doesn't satisfy what @atlaskit/toggle requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (pe223a) with version 18.2.0, which doesn't satisfy what @atlaskit/menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (p7f140) with version 18.2.0, which doesn't satisfy what @atlaskit/popup requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (p21edf) with version 18.2.0, which doesn't satisfy what @atlaskit/portal requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (p6f1aa) with version 18.2.0, which doesn't satisfy what @atlaskit/dropdown-menu requests
➤ YN0060: │ @ironclad/rivet-app@workspace:packages/app provides react-dom (p3d925) with version 18.2.0, which doesn't satisfy what @atlaskit/select and some of its descendants request
➤ YN0002: │ @ironclad/rivet-core@workspace:packages/core doesn't provide @types/node (p2a077), requested by ts-node
➤ YN0002: │ @ironclad/rivet-core@workspace:packages/core doesn't provide @typescript-eslint/parser (pcafdb), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ @ironclad/rivet-node@workspace:packages/node doesn't provide @typescript-eslint/parser (p5d7b8), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ @ironclad/rivet@workspace:. doesn't provide @typescript-eslint/parser (p14739), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ @ironclad/trivet@workspace:packages/trivet doesn't provide @typescript-eslint/parser (pc3af5), requested by @typescript-eslint/eslint-plugin
➤ YN0060: │ docs@workspace:packages/docs provides react (p4e1cc) with version 18.2.0, which doesn't satisfy what @docusaurus/types requests
➤ YN0060: │ docs@workspace:packages/docs provides react (p9d5e3) with version 18.2.0, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0060: │ docs@workspace:packages/docs provides react (p1334f) with version 18.2.0, which doesn't satisfy what @mdx-js/react requests
➤ YN0060: │ docs@workspace:packages/docs provides react (p0e283) with version 18.2.0, which doesn't satisfy what @docusaurus/preset-classic and some of its descendants request
➤ YN0060: │ docs@workspace:packages/docs provides react-dom (p1a640) with version 18.2.0, which doesn't satisfy what @docusaurus/types requests
➤ YN0060: │ docs@workspace:packages/docs provides react-dom (p47f6f) with version 18.2.0, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0060: │ docs@workspace:packages/docs provides react-dom (p45133) with version 18.2.0, which doesn't satisfy what @docusaurus/preset-classic and some of its descendants request
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [388c2] doesn't provide @babel/plugin-syntax-flow (p32599), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [388c2] doesn't provide @babel/plugin-transform-react-jsx (pff2ca), requested by eslint-plugin-flowtype
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 265ms
➤ YN0000: ┌ Fetch step
➤ YN0019: │ @esbuild-darwin-arm64-npm-0.18.17-4da6dfeef9-9.zip appears to be unused - removing
➤ YN0019: │ @esbuild-darwin-arm64-npm-0.19.1-f737930702-9.zip appears to be unused - removing
➤ YN0019: │ @swc-core-darwin-arm64-npm-1.3.71-5ea24a12db-9.zip appears to be unused - removing
➤ YN0019: │ @tauri-apps-cli-darwin-arm64-npm-1.4.0-07239c8e68-9.zip appears to be unused - removing
➤ YN0019: │ fsevents-patch-19706e7e35-9.zip appears to be unused - removing
➤ YN0000: └ Completed in 0s 317ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.18.17 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.3.71 [36b10] must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.17.19 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.19.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.32.0 must be built because it never has been before or the last one failed
➤ YN0008: │ protobufjs@npm:7.2.4 must be rebuilt because its dependency tree changed
➤ YN0007: │ core-js-pure@npm:3.31.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 4s 998ms
➤ YN0000: Done with warnings in 5s 835ms
rivet$ yarn dev
Bundling to bin/executor-bundle.js...
Compiling to native binary for linux...
> pkg@5.8.1
> Warning Cannot resolve 'config.extends'
/rivet/packages/app-executor/bin/executor-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'path2'
/rivet/packages/app-executor/bin/executor-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
Copied dist/rivet-app-executor to dist/app-executor-x86_64-unknown-linux-gnu for tauri sidecar
     Running BeforeDevCommand (`yarn start`)

  VITE v4.4.7  ready in 392 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
        Info Watching /rivet/packages/app/src-tauri for changes...
   Compiling app v0.1.0 (/rivet/packages/app/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 11.40s
4:28:07 PM [vite] warning: 
/rivet/packages/app/src/hooks/useProjectPlugins.ts
28 |                throw new Error(`Unknown built-in plugin ${name}.`);
29 |              }).with({ type: "uri" }, async (spec2) => {
30 |                const plugin = (await import(spec2.uri)).default;
   |                                             ^
31 |                if (typeof plugin !== "function") {
32 |                  throw new Error(`Plugin ${spec2.id} is not a function`);
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

  Plugin: vite:import-analysis
  File: /rivet/packages/app/src/hooks/useProjectPlugins.ts
4:28:08 PM [vite] warning: 
/rivet/packages/app/src/components/ProjectPluginConfiguration.tsx
292|        }
293|        toggleLoadingPlugin.setRight();
294|        const plugin = await import(pluginUri);
   |                                    ^
295|        if (!plugin) {
296|          throw new Error(`Failed to load plugin from ${pluginUri}`);
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

  Plugin: vite:import-analysis
  File: /rivet/packages/app/src/components/ProjectPluginConfiguration.tsx
